#!/usr/bin/env bash
# SPDX-License-Identifier: LGPL-2.1-or-later
#
# abi-snapshot.sh — capture / verify the LibreAgent public C++ API surface.
#
# LibreAgent ships a single static archive (libLibreAgentCore.a) exposing
# the platform-neutral agent core behind the LibreSCRS::Agent namespace;
# consumers link it through the installed LibreAgent::Core CONFIG package.
# The frozen surface is the demangled set of T-binding (global text)
# symbols in the LibreSCRS::Agent:: namespace.
#
# Unlike a shared object with visibility controls, a static archive also
# carries every internal TU-level helper as a T-binding symbol. The
# pipeline therefore filters the demangled list to the LibreSCRS::Agent::
# prefix: that namespace is the public, frozen API; anything outside it is
# an implementation detail free to churn between releases.
#
# This script generates a stable, sorted, human-readable text artefact
# checked into the tree at:
#   ci/abi/4.x-baseline.txt
#
# Use --check to compare a fresh build against the baseline; the script
# fails non-zero on any difference. Use --update to regenerate the baseline.
#
# Why text not abigail/abicompat: the API is plain C++23 value types,
# interfaces and flows. A demangled T-symbol diff catches the cases that
# matter — function added / removed / signature changed — with a one-line
# review per change, and none of the cosmetic XML noise (typedef churn,
# unsigned-int vs size_t under different toolchains) an abidiff produces.
#
# Usage:
#   abi-snapshot.sh [--check|--update] [BUILD_DIR]
#
# Default action: --check. Default BUILD_DIR: build.

set -euo pipefail

# Force a deterministic, locale-independent sort so the baseline lines
# up byte-for-byte across developer machines and CI runners. Without
# LC_ALL=C, glibc's default UTF-8 collation interleaves alphabetic and
# punctuation differently than ASCII (e.g. en_US.UTF-8 sorts
# `…CancelSource const&)` before `…CancelSource&&)` while sr_RS sorts
# the other way), and any diff against the baseline is pure noise.
export LC_ALL=C

ACTION="check"
BUILD_DIR="build"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --check) ACTION="check"; shift ;;
        --update) ACTION="update"; shift ;;
        -h|--help)
            sed -n '2,/^$/p' "$0" | sed 's/^# \?//'
            exit 0
            ;;
        *) BUILD_DIR="$1"; shift ;;
    esac
done

if [[ ! -d "$BUILD_DIR" ]]; then
    echo "ERROR: build dir '$BUILD_DIR' not found" >&2
    exit 2
fi

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
BASELINE="${REPO_ROOT}/ci/abi/4.x-baseline.txt"
SCRATCH="$(mktemp -d)"
trap 'rm -rf "$SCRATCH"' EXIT

snapshot="${SCRATCH}/snapshot.txt"

archive="$(find "$BUILD_DIR" -name 'libLibreAgentCore.a' | sort | head -n 1)"
if [[ -z "$archive" ]]; then
    echo "ERROR: libLibreAgentCore.a not found under '$BUILD_DIR' — build first" >&2
    exit 2
fi

symbols="$(nm -U "$archive" 2>/dev/null \
    | awk '$2 == "T" { print $3 }' \
    | c++filt 2>/dev/null \
    | { grep '^LibreSCRS::Agent::' || true; } \
    | sort -u)"

# An empty filtered surface can only mean the archive is broken or the
# nm | c++filt pipeline failed — never a legitimate state for this repo.
# Fail loudly rather than let an empty snapshot silently pass --check or
# become the baseline via --update.
if [[ -z "$symbols" ]]; then
    echo "ERROR: no LibreSCRS::Agent:: T-binding symbols found in '$archive'" >&2
    echo "       (broken archive, or nm/c++filt failed). Refusing to emit an" >&2
    echo "       empty snapshot." >&2
    exit 2
fi

{
    echo "# LibreAgent public API snapshot"
    echo "# Generated by ci/scripts/abi-snapshot.sh"
    echo "# Format: one demangled T-binding symbol per line, sorted; section"
    echo "# header line '== <archive basename> =='."
    echo "# Re-generate with: ci/scripts/abi-snapshot.sh --update <build_dir>"
    echo "# Diff a fresh build against this baseline with: ci/scripts/abi-snapshot.sh --check"
    echo "#"
    echo "# Surface: T-binding symbols of the static archive libLibreAgentCore.a,"
    echo "# filtered to the public LibreSCRS::Agent:: namespace. A static archive"
    echo "# also carries internal TU-level helpers as T-binding symbols; only the"
    echo "# public namespace is frozen, so only it is snapshotted."
    echo
    echo "== libLibreAgentCore.a =="
    printf '%s\n' "$symbols"
} > "$snapshot"

case "$ACTION" in
    update)
        mkdir -p "$(dirname "$BASELINE")"
        cp "$snapshot" "$BASELINE"
        echo "Wrote ABI baseline: $BASELINE"
        wc -l "$BASELINE"
        ;;
    check)
        if [[ ! -f "$BASELINE" ]]; then
            echo "ERROR: baseline not found at $BASELINE" >&2
            echo "       Run 'ci/scripts/abi-snapshot.sh --update <build_dir>' to capture." >&2
            exit 2
        fi
        if diff -u "$BASELINE" "$snapshot" > "${SCRATCH}/abi-diff.txt"; then
            echo "ABI snapshot matches baseline ($(wc -l < "$BASELINE") lines)."
            exit 0
        else
            echo "ABI DRIFT detected vs $BASELINE:" >&2
            cat "${SCRATCH}/abi-diff.txt" >&2
            echo >&2
            echo "If this drift is intentional (a new public API addition or" >&2
            echo "an explicit breaking change for a major bump):" >&2
            echo "   ci/scripts/abi-snapshot.sh --update $BUILD_DIR" >&2
            exit 1
        fi
        ;;
esac
